apiVersion: v1
kind: Pod
metadata:
  name: echo-server-pod
  labels:
    app: echo-server
spec:
  containers:
  - name: echo-server-container
    image: ealen/echo-server
    ports:
    - containerPort: 80
